export const ZohoLeadData = {
    "Z_Last_Sold_Price":null,
    "Owner":{
       "name":"Dan Cohen",
       "id":"4437205000000288232",
       "email":"dan@homesalesclub.com"
    },
    "GCLID":null,
    "Comps_PDF":null,
    "Convoso_List_ID":"12470",
    "OFFER_PRICE1":0,
    "$state":"save",
    "Address_1":"1409 Oakwood Avenue",
    "$process_flow":false,
    "Address_2":null,
    "Occupancy":null,
    "Ad_Network":null,
    "Mortgage_Remaining":null,
    "High_Range_62":128650,
    "KEYWORDID":null,
    "id":"443720500004123840000",
    "$approval":{
       "delegate":false,
       "approve":false,
       "reject":false,
       "resubmit":false
    },
    "Requires_Movers":null,
    "Cost_per_Click":0,
    "Closing_Costs":null,
    "Created_Time":"2020-07-28T17:54:32-04:00",
    "Sell_House_Today":null,
    "Personal_Property_To_Remove":null,
    "Is_This_A_Cell_Phone":null,
    "Seller_Email_2":null,
    "Z_Use_Code":"SingleFamily",
    "Holding_Cost":0,
    "Bedrooms":null,
    "Ad_Click_Date":null,
    "Earnest_Money_Deposit":null,
    "Country":null,
    "Z_Zestimate":207500,
    "Created_By":{
       "name":"Home Sales Club",
       "id":"4437205000001474003",
       "email":"accounts@homesalesclub.com"
    },
    "Lead_Creation_Period":null,
    "Property_Condition_Notes":null,
    "Primary_Decision_Maker":null,
    "Reason_for_Selling":"Downsizing",
    "Ad":null,
    "Z_Bedrooms":5,
    "Search_Partner_Network":null,
    "Resale_Price_Over_200k_ARV":null,
    "$review_process":{
       "approve":false,
       "reject":false,
       "resubmit":false
    },
    "Z_Finished_Sq_Ft":"1599",
    "HO_Conversion":"YES",
    "Salutation":null,
    "HO_Lander_ID":"Lander Dir: 8",
    "ADGROUPID":null,
    "Full_Name":"Kerry Esparza",
    "Listed_With_Agent":null,
    "Lead_Status":"Wants Retail",
    "Address_Concat":null,
    "Property_Status_Notes":null,
    "Seller_Name_2":null,
    "Level_of_Rehab":null,
    "Months_Behind_on_Mortgage":null,
    "ADID":null,
    "Information_is_complete_and_ready_to_send":"No",
    "HO_S5":null,
    "HO_S4":null,
    "HO_S3":null,
    "Keyword":null,
    "Trigger_Add_Seller_Leads_to_List":false,
    "HO_S2":null,
    "Convoso_Status":"WR",
    "HO_S1":"GoogleDisplayRemarketing",
    "Risk_Assessment":0,
    "Trigger_Zillow":false,
    "$orchestration":false,
    "Acquisition_Agent":{
       "name":"Dan Cohen",
       "id":"4437205000000288232"
    },
    "Timestamp_Contract_Triggered":null,
    "Ad_Campaign_Name":null,
    "Tag":[
    ],
    "Reason_for_Conversion_Failure":null,
    "Home_Sale_Timeframe":null,
    "Email":"Kerry.esparza07@gmail.com",
    "$currency_symbol":"$",
    "Global_ID":"Z4SL7EG9LNN0EABIK3QQM03PXY32SZZ7",
    "Interested_In_Solar":null,
    "Last_Activity_Time":"2020-07-28T17:59:58-04:00",
    "Trigger":false,
    "Self_Estimated_Value":225000,
    "$converted":false,
    "Commission_Closing_Cost":0,
    "Zip_Code":"89030",
    "Profit":0,
    "$approved":true,
    "Conversion_Exported_On":null,
    "Z_Last_Sold_Date":null,
    "Second_Seller":null,
    "Click_Type":null,
    "Other_Terms":null,
    "Z_Year_Built":1954,
    "$editable":true,
    "Property_Type":null,
    "Converted_By":null,
    "City":"North Las Vegas",
    "AdGroup_Name":null,
    "Title_Company":null,
    "Current_Amount_Seller_Will_Accept":null,
    "ZCAMPAIGNID":null,
    "Contract_Offer_Amount":null,
    "HO_Pub_ID":"1",
    "Z_Bathrooms":2,
    "Rehab_Budget1":0,
    "Z_Property_Link":"https://www.zillow.com/homedetails/1409-Oakwood-Ave-North-Las-Vegas-NV-89030/6994353_zpid/",
    "HO_Transaction_ID":"CjwKCAjwmf_4BRABEiwAGhDfSU8t3fMxb7-FX5bAhVJEWVvG_nWFJF2F4sq28JGdyMoJSJ5-T4tRoBoCI1sQAvD_BwE",
    "Trigger_Add_to_Dialer":false,
    "First_Name":null,
    "Ownership_Length":null,
    "Conversion_Export_Status":null,
    "Cost_per_Conversion":0,
    "State1":"NV",
    "$review":null,
    "Convoso_Lead_ID":"3498",
    "GADCONFIGID":null,
    "Phone":"17024191752",
    "Low_Range_42":87150,
    "Call_Status":"Contacted",
    "Notes1":null,
    "Closing_Number_of_Days":null,
    "Modified_Time":"2020-07-28T17:59:58-04:00",
    "$converted_detail":{
    },
    "Device_Type":null,
    "Inspection_Period":null,
    "Last_Name":"Kerry Esparza",
    "Square_Feet":null,
    "$in_merge":false,
    "Bathrooms":null,
    "zoho_etl_record_type":"leads"
};

export const ZohoUpdatedLeadData = {
    "id":"443720500004123840000",
    "Global_ID":"Z4SL7EG9LNN0EABIK3QQM03PXY32SZZ7",
    "High_Range_62":200500,
    "zoho_etl_record_type":"leads"
};

export const ZohoDealData = {
   "id":"987654321",
   "Global_ID":"MNOPQRSTUBWXYZ",
   "Z_Zestimate": 200000,
   "zoho_etl_record_type":"deals"
};

export const ZohoUpdatedDealData = {
   "id":"987654321",
   "Global_ID":"MNOPQRSTUBWXYZ",
   "Z_Zestimate": 255000,
   "zoho_etl_record_type":"deals"
};